# Use the latest version of the python image from Docker Hub
FROM python:latest

# Define the working directory within the container
WORKDIR /app

# Copy files from local directory into container directory
COPY hello_world.py /app

# Run the application
CMD ["python", "./hello_world.py"]
